export const LeagueObjs = [
        {
            league_name: "Premier League", 
            league_id: 2790,
            flag: "https://media.api-sports.io/flags/gb.svg",
            logo: "https://media.api-sports.io/football/leagues/39.png",
            fixtures: [],
        },
        {
            league_name: "Primera Division",
            league_id: 2833,
            flag: "https://media.api-sports.io/flags/es.svg",
            logo: "https://media.api-sports.io/football/leagues/140.png",
            fixtures: [],
        },
        {
            league_name: "Bundesliga",
            league_id: 2755,
            flag: "https://media.api-sports.io/flags/de.svg",
            logo: "https://media.api-sports.io/football/leagues/78.png",
            fixtures: [],
        },
        {
            league_name: "Serie A",
            league_id: 2857,
            flag: "https://media.api-sports.io/flags/it.svg",
            logo: "https://media.api-sports.io/football/leagues/135.png",
            fixtures: [],
        },
        {
            league_name: "Primeira Liga",
            league_id: 2826,
            flag: "https://media.api-sports.io/flags/pt.svg",
            logo: "https://media.api-sports.io/football/leagues/94.png",
            fixtures: [],
        },
        {
            league_name: "Ligue 1",
            league_id: 2664,
            flag: "https://media.api-sports.io/flags/fr.svg",
            logo: "https://media.api-sports.io/football/leagues/61.png",
            fixtures: [],
        },
        {
            league_name: "Eredivisie",
            league_id: 2673,
            flag: "https://media.api-sports.io/flags/nl.svg",
            logo: "https://media.api-sports.io/football/leagues/88.png",
            fixtures: [],
        },
        {
            league_name: "FA Cup",
            league_id: 2791,
            flag: "https://media.api-sports.io/flags/gb.svg",
            logo: "https://media.api-sports.io/football/leagues/45.png",
            fixtures: [],
        },
        {
            league_name: "Championship",
            league_id: 2794,
            flag: "https://media.api-sports.io/flags/gb.svg",
            logo: "https://media.api-sports.io/football/leagues/40.png",
            fixtures: [],
        },
    ]
